name = "Slop Craft"
author = "epeterson"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75d63aaf6dea3f1c2ecde34661f7a6aca7fd95ca9a23887a2f20987a4bf5a0f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
