name = "Slop Craft"
author = "epeterson"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90960a29ff89f6547a3a05721e83d0d868622d688dde2ce089808ed869c68205"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
