[blocks]
	block = []
	display_block = ["create:bar_of_chocolate|plate|6", "create:builders_tea|bottle|1|10|true", "create:sweet_roll|plate|4", "farmersdelight:pumpkin_pie_slice|small_plate|1", "minecraft:cake|plate|1", "minecraft:pumpkin_pie|plate|1"]
	fluid = []

[items]
	item = []
	hide_items = []
